CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS scores
(
    id    INTEGER PRIMARY KEY,
    time  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    score INTEGER  NOT NULL
);
